const { Resend } = require("resend");

const resend = new Resend(process.env.RESEND_API_KEY);

async function sendEmail(to, summary) {
  if (!process.env.RESEND_API_KEY) {
    throw new Error("RESEND_API_KEY is not configured.");
  }

  const htmlBody = `
    <div style="font-family: 'Segoe UI', sans-serif; max-width: 680px; margin: 0 auto; padding: 40px 24px; background: #0a0a0f; color: #f1f5f9;">
      <div style="display:flex; align-items:center; gap:10px; margin-bottom: 32px;">
        <span style="font-size:32px;">🐇</span>
        <div>
          <h1 style="font-size: 20px; font-weight: 800; margin: 0; color: #fff;">Rabbitt AI</h1>
          <p style="margin: 0; color: #6c3bff; font-size: 13px; font-weight: 600;">Sales Insight Report</p>
        </div>
      </div>

      <div style="background: linear-gradient(135deg, #6c3bff22, #ff3b9422); border: 1px solid #6c3bff44; border-radius: 12px; padding: 24px; margin-bottom: 24px;">
        <p style="margin: 0; color: #a78bfa; font-size: 13px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px;">Generated on</p>
        <p style="margin: 4px 0 0; color: #f1f5f9; font-size: 15px;">${new Date().toLocaleDateString("en-US", {
          weekday: "long", year: "numeric", month: "long", day: "numeric",
        })}</p>
      </div>

      <div style="line-height: 1.9; font-size: 16px; color: #cbd5e1; white-space: pre-wrap;">
        ${summary.replace(/\n/g, "<br/>")}
      </div>

      <hr style="margin: 40px 0; border: none; border-top: 1px solid #1e293b;" />
      <p style="font-size: 12px; color: #334155; text-align: center;">
        Automatically generated by Rabbitt AI Sales Insight Automator · Powered by Google Gemini
      </p>
    </div>
  `;

  const { error } = await resend.emails.send({
    from: process.env.FROM_EMAIL || "Sales Insights <onboarding@resend.dev>",
    to: [to],
    subject: `🐇 Rabbitt AI — Sales Insight Report · ${new Date().toLocaleDateString()}`,
    html: htmlBody,
  });

  if (error) {
    throw new Error(`Email delivery failed: ${error.message}`);
  }
}

module.exports = { sendEmail };